create table public.events (
    id bigint generated by default as identity primary key,
    title text not null,
    category text not null,
    date date not null,
    time time without time zone not null,
    location text not null,
    price numeric(10, 2) not null default 0 check (price >= 0),
    created_at timestamptz not null default now()
);

alter table public.events enable row level security;

revoke all on table public.events from anon, authenticated;
grant select on table public.events to anon, authenticated;
grant insert, update, delete on table public.events to authenticated;
grant usage, select on sequence public.events_id_seq to authenticated;

create policy "Public can read events"
    on public.events for select
    to anon, authenticated
    using (true);

create policy "Admins can add events"
    on public.events for insert
    to authenticated
    with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admins can update events"
    on public.events for update
    to authenticated
    using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
    with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admins can delete events"
    on public.events for delete
    to authenticated
    using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

insert into public.events (title, category, date, time, location, price)
values
    ('Детский спектакль', 'Дети', '2026-10-10', '12:00', 'Уфа, ГКЗ Башкортостан', 1200),
    ('Концерт', 'Музыка', '2026-10-15', '19:00', 'Уфа, Тинькофф Холл', 2500),
    ('Мастер-класс по керамике', 'Обучение', '2026-10-18', '15:00', 'Уфа, Арт-пространство', 1800);
